### PR TITLE
grid layout modified

### PR DESCRIPTION
**Pull request by ayush9**

### CODE REVIEW

**Comment by panwarab** [comment]
@ayush9  please allow me sometime, will get back asap.

**Comment by panwarab** [comment]
@ayush9  this error is showing up :: Error:(33, 13) Failed to resolve: com.etsy.android.grid:library:1.0.5
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by panwarab** [comment]
@ayush9  I think due to different configurations build is failing. I advice you to please commit only java files. I will do a commit applying the staggered view library. You can re-commit it using that.

**Comment by panwarab** [comment]
@ayush9  advice:: clean the project before commiting

**Comment by panwarab** [comment]
@ayush9  good  work, but remember only to merge java files only to projects. Cool. :)

**Comment by ayush9** [comment]
Thankyou :)

**Comment by panwarab** [comment]
@ayush9  in the meanwhile if you have projects that can be worked out, do let me know. A word of advice:- please  complete your project profiles and README.md's , It helps a lot for , a recruiter, let's say to have an overview of your work. 👍

**Pull request merged**
